pipeline {
    agent any

    stages {
        stage('Prepare environment') {
            steps {
                echo 'Creating gradle wrapper...'
                sh 'gradle wrapper'
            }
        }
        stage('Create Database') {
            steps {
                echo 'Creating Database...'
                sh './gradlew createDatabase'
            }
        }
        stage('Build and Test') {
            steps {
                echo 'Building and unit testing...'
                sh './gradlew clean build'
            }
        }
        stage('Sonarqube') {
            steps {
                echo 'Checking quality with Sonarqube...'
                sh './gradlew sonarqube'
            }
        }
    }
}
