pipeline {
    agent any

    stages {
        stage('Prepare environment') {
            steps {
                echo 'Creating gradle wrapper...'
                sh 'gradle wrapper --gradle-version=5.6.3'

                echo 'Bringing up database server...'
                sh './gradlew runDatabaseDocker'
            }
        }
        stage('Create Database') {
            steps {
                echo 'Creating Database...'
                sh './gradlew createDatabase'
            }
        }
        stage('Build and Test') {
            steps {
                echo 'Building and unit testing...'
                sh './gradlew clean build'
            }
        }
        stage('Sonarqube') {
            steps {
                echo 'Checking quality with Sonarqube...'
                sh './gradlew sonarqube'
            }
        }
        stage('Artifacts') {
            steps {
                echo 'Zipping deployment artifacts'
                sh './gradlew zipArtifacts'
            }
        }
    }
}
