USE `ranking` /*!40100 DEFAULT CHARACTER SET utf8mb4 */

CREATE TABLE `user` (
    `id` INT(11) NOT NULL UNIQUE PRIMARY KEY,
    `email` VARCHAR(128) NOT NULL UNIQUE,
    `username` VARCHAR(128) NOT NULL UNIQUE,
    `level` TINYINT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
